name: Bug Report
description: File a bug report.
title: "Bug: "
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: |
        #### Bug Description
        ...

        #### Expected Behavior
        ...

        #### Steps to Reproduce
        1. ...
        2. ...
        3. ...

        #### Additional Context
        Add any other context about the problem here.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: If applicable, what version of the game are you running?
      options:
        - 0.1.0
      default: 0
    validations:
      required: false
  - type: dropdown
    id: aspect
    attributes:
      label: Which aspect(s) of the project is this bug affecting?
      description: See [this wiki page](https://github.com/sloukit/pydew-valley-uzh/wiki/How-to-choose-labels) for more information on how to choose labels.
      multiple: true
      options:
        - "area: code quality"
        - "area: dependencies"
        - "area: documentation"
        - "area: publishing"
        - game-art
        - game-audio
        - game-design
        - game-level-design
        - game-ui
        - game-gameplay
        - game-playtesting
        - game-ai
        - game-help
        - game-story
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please upload any relevant screenshots.
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
